---

- name: Inlcude os-specific tasks
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Create an EC2 key
  ec2_key:
    name: "{{ ec2_name }}-{{ env }}-key"
    region: "{{ region }}"
  register: ec2_key

- name: Save private key
  copy: content="{{ ec2_key.key.private_key }}" dest="{{ mydest }}" mode=0600
  when: ec2_key.changed

- name: Create an EC2 instance
  ec2:
    key_name: "{{ ec2_name }}-{{ env }}-key"
    region: "{{ region }}"
    group: "{{ secgroup }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami }}"
    wait: yes
    instance_tags:
        Name: "{{ ec2_instname }}"
        env: "{{ env }}"
    count_tag: env
    exact_count: 1
    vpc_subnet_id: "{{ ec2_subnetid }}"
    assign_public_ip: yes
  register: ec2

- name: Add the newly created EC2 instance(s) to host file 
  lineinfile: dest={{ hostpath }}
              regexp={{ item.public_ip }} 
              insertafter="[docker]" 
              line="{{ item.public_ip }} {{ hoststring }}"
              state=present
  with_items: "{{ ec2.instances }}"

- wait_for: path={{ hostpath }} search_regex={{ hoststring }}

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
  with_items: "{{ ec2.instances }}"
